name: Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install Node.js dependencies
      run: npm install
    - name: Lint with ESLint
      run: npm run lint
    - name: Test
      run: |
        test/prepare.sh
        npm test
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
